import type { Metadata } from "next";
import Navbar from "@/components/ProfileNavbar";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <div className="flex h-screen">
      <Sidebar />
      <main className="flex-1 md:p-8 pt-2 p-8 overflow-y-auto">
        <Navbar />
        {children}
      </main>
    </div>
  );
}
