import type { Metadata } from "next";
import { Corben, Mulish } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import TrpcProvider from "@/lib/trpc/Provider";
import { cookies } from "next/headers";
import Navbar from "@/components/Navbar";
import NuLogoBackground from "@/components/NuLogoBackground";

import { client } from "../../sanity/lib/client";
// const inter = Inter({ subsets: ["latin"] });

const corben = Corben({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-corben" });
const mulish = Mulish({ subsets: ["latin"], variable: "--font-mulish" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ locale: "fr" }, { locale: "en" }];
}

export async function getInfo() {
  const banner = await client.fetch(`*[_type=='navigationBanner'][0]`);
  // console.log(banner);
  return banner;
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { enabled, messages } = await getInfo();

  return (
    <html lang={locale}>
      <body className={`${corben.variable} ${mulish.variable} font-mulish`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* disableTransitionOnChange */}
          <TrpcProvider cookies={cookies().toString()}>
            <div className={`w-full min-h-screen relative `}>
              <NuLogoBackground />
              <Navbar enabled={enabled} messages={messages} />
              <div style={{ backgroundColor: "black" }} className="w-1/2 bg-black relative mx-auto mt-60 h-48"></div>
              {/* <h1 className="w-fit relative mx-auto">HELLO THIS IS A TEST</h1> */}
              {/* {children} */}
            </div>
          </TrpcProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
